### ISSUE TITLE
Mode 4 (Real Reset of krbtgt) Has Less Information Than Mode 3

### ISSUE THREAD

**Issue by aakash-shah** [microsoft/New-KrbtgtKeys.ps1#2]
Hello! I noticed that when running Mode 3 (Simulation Mode with krbtgt_TEST), it provides some useful information when compared to Mode 4 (Real Reset Mode). For instance, Mode 3 states:

- "Resetting KrbTgt Accnt Password Means.: 'MAJOR DOMAIN WIDE IMPACT'"

- Date/Time N-1 Kerberos Tickets........: '<Date>'

It would be helped to include more warnings when resetting the real krbtgt account in Mode 4. If I have misunderstood something though, please let me know.

I am using the new version 2 committed on May 12.

Thanks!

**Comment by cchapin-ms** [comment]
Thanks for the feedback, we will look at incorporating the change in a future release.
