### ISSUE TITLE
This script must be executed as Administrator

### ISSUE THREAD

**Issue by itpro-tips** [microsoft/New-KrbtgtKeys.ps1#6]
Hello,

If PowerShell is not running as admin, the _testAdminRole_ always failed because
_[Security.Principal.WindowsIdentity]::GetCurrent()_ doesn't return high privileged groups.

Maybe add a check to be sure PowerShell is running as admin ? (_https://itpro-tips.com/2019/check-if-a-powershell-script-is-run-as-administrator/_)

**Comment by cchapin-ms** [comment]
PowerShell does not have to run as admin in all environments. Feel free to submit a pull request with updated code.
