### ISSUE TITLE
Automation / Scheduled Task

### ISSUE THREAD

**Issue by mubix** [microsoft/New-KrbtgtKeys.ps1#8]
Is there a way to make this script something that could be run in an automated format without user interaction on a regular basis?

**Comment by cchapin-ms** [comment]
The security guidance on this is that it should not be configured as an automated task due to the sensitivity and criticality of the processes involved.

**Comment by truekonrads** [comment]
But why is the guidance not to automate it. Is there an element of luck involved? What is the difference if human does it or a robot? I feel that this is closed as “too difficult, won’t fix” or “for reasons beyond grasp of mere mortals”. 

Please reopen

**Comment by cwmoriarty** [comment]
Feel free to write a PR for this. It's not a complicated interface. The stated goal of this utility is to guide an administrator in confirming this change will occur safely.
